arrowParens: always
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxSingleQuote: false
overrides:
  - files: 
      - '*.yml'
      - '*.json'
    options:
      semi: false
      singleQuote: false
  - files: 
      - '*.html'
    options:
      semi: false
      singleQuote: false
      tabWidth: 4
parser: typescript
printWidth: 80
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
